import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Divider } from '@mui/material';
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { apiBaseUrl } from '../env';
import LineWeight from '@mui/icons-material/LineWeight';
import TextField from '@mui/material/TextField';



const Home: NextPage = () => {
  const [zipInProgress, setZipInProgres ] = useState<boolean>(false)
  const []
  const [share, setShare] = useState<boolean>(false)
  
  const resetState = () => {
    setZipInProgres(false)
    setShare(false)
  }

  const handleSeek = async (e: any) => {
    e.preventDefault()
    setSeekInProgress(true)
    setExtractedMessage("If it's taking too long, it's likely that the hidden message doesn't exist.")
    let formData = new FormData()
    formData.append('file', imageForSeek)
    const response = await fetch(`${apiBaseUrl}/seek`, {
      method: 'POST',
      body: formData
    }).then(res => res.json())
    .then(data => {
      setSeekInProgress(false)
      setExtractedMessage(data.message)
    })
  }

  return (
    <>
    <div className={styles.navigation}>
      <div className={styles.navTitle}>
        ZipLink
      </div>
    </div>
    <div className={styles.container}>
      <Head>
        <title>Steganography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Make short your link and share it with your friends
        <Divider style={{width:'100%', marginTop:'1.8em', marginBottom: '1.8em'}} />
        <div className={styles.inputGroup}>
        <TextField id="standard-basic" label="URL" variant="standard"/>
        <Button variant="outlined" size="large" >
          ZIP&nbsp;<LineWeight></LineWeight>
        </Button>
        </div>
      </main>
      <footer className={styles.footer}>
        D3fau1t: ZipLink
      </footer>
    </div>
    </>
  )
}

export default Home