import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Divider } from '@mui/material';
import styles from '../styles/Home.module.css'
import { useRef } from 'react'
import { apiBaseUrl } from '../env';
import LineWeight from '@mui/icons-material/LineWeight';
import TextField from '@mui/material/TextField';



const Home: NextPage = () => {
  const inputRef = useRef<HTMLInputElement>(null)

  const getUrlAndZip = async (e: any) => {
    e.preventDefault()
    if (!inputRef.current) {
      return
    }
    const url = inputRef.current.value
    const response = await fetch(`${apiBaseUrl}/url`, {
      method: 'POST',
      body: JSON.stringify({ 'url': url }),
    }).then(res => res.json())
    console.log(response)
  }

  return (
    <>
    <div className={styles.navigation}>
      <div className={styles.navTitle}>
        ZipLink
      </div>
    </div>
    <div className={styles.container}>
      <Head>
        <title>ZipLink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Make short your link and share it with your friends
        <Divider style={{width:'100%', marginTop:'1.8em', marginBottom: '1.8em'}} />
        <div className={styles.inputGroup}>
        <TextField inputRef={inputRef} name="url" id="url" label="URL" variant="standard"/>
        <Button variant="outlined" size="large" onClick={getUrlAndZip}>
          ZIP&nbsp;<LineWeight></LineWeight>
        </Button>
        </div>
      </main>
      <footer className={styles.footer}>
        D3fau1t: ZipLink
      </footer>
    </div>
    </>
  )
}

export default Home